### ISSUE TITLE
i18n bug UndefinedError: '_' is undefined

### ISSUE THREAD

**Issue by creatingwake** [inveniosoftware/flask-security-fork#39]
Login template throwing an exception due to the i18n markup introduced in #33 
---
Environment:
Mac OS 10.11.6
Python 2.7
Flask==0.12.2
Flask-BabelEx==0.9.3
Flask-Login==0.4.0
Flask-Mail==0.9.1
Flask-Principal==0.4.0
-e git+https://github.com/inveniosoftware/flask-security-fork.git@cb2b3bb080dde4ec7f207522ca7d901e095e5b84#egg=Flask_Security_Fork
Flask-WTF==0.14.2
itsdangerous==0.24
Jinja2==2.9.6
---
Traceback (most recent call last)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
return self.wsgi_app(environ, start_response)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
response = self.handle_exception(e)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/src/flask-security/flask_security/decorators.py", line 230, in wrapper
return f(*args, **kwargs)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/src/flask-security/flask_security/views.py", line 88, in login
**_ctx('login'))
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/src/flask-security/flask_security/core.py", line 517, in render_template
return render_template(*args, **kwargs)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
context, ctx.app)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
rv = template.render(context)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
return self.environment.handle_exception(exc_info, True)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
reraise(exc_type, exc_value, tb)
File "/Users/paulmorris/Documents/dev/Virtualenvs/mwi-tool/src/flask-security/flask_security/templates/security/login_user.html", line 3, in top-level template code
<h1>{{ _('Login') }}</h1>
UndefinedError: '_' is undefined

**Comment by jirikuncar** [comment]
@creatingwake have you initialised Flask-BabelEx extension?

**Comment by creatingwake** [comment]
@jirikuncar no Flask-BabelEx isn't initialised in my app as I don't wish to implement localisation.
Does this update mean I now **_have_** to, or can defaults be provided in flask-security-fork

**Comment by jirikuncar** [comment]
We can add a fallback then.

**Comment by jirikuncar** [comment]
@creatingwake the bugfix is available in upstream https://github.com/mattupstate/flask-security/issues/649.
